package com.oneapm.atomikos.a.domain;

import java.util.ArrayList;
import java.util.List;

public class TblACriteria {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table tbl_a
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table tbl_a
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table tbl_a
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_a
     * @mbggenerated
     */
    public TblACriteria() {
        oredCriteria=new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_a
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause=orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_a
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_a
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct=distinct;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_a
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_a
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_a
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_a
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria=createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_a
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria=createCriteriaInternal();
        if(oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_a
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria=new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_a
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause=null;
        distinct=false;
    }

    /**
     * This class was generated by MyBatis Generator. This class corresponds to the database table tbl_a
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {

        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria=new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if(condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if(value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if(value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andA1IsNull() {
            addCriterion("a1 is null");
            return (Criteria)this;
        }

        public Criteria andA1IsNotNull() {
            addCriterion("a1 is not null");
            return (Criteria)this;
        }

        public Criteria andA1EqualTo(Integer value) {
            addCriterion("a1 =", value, "a1");
            return (Criteria)this;
        }

        public Criteria andA1NotEqualTo(Integer value) {
            addCriterion("a1 <>", value, "a1");
            return (Criteria)this;
        }

        public Criteria andA1GreaterThan(Integer value) {
            addCriterion("a1 >", value, "a1");
            return (Criteria)this;
        }

        public Criteria andA1GreaterThanOrEqualTo(Integer value) {
            addCriterion("a1 >=", value, "a1");
            return (Criteria)this;
        }

        public Criteria andA1LessThan(Integer value) {
            addCriterion("a1 <", value, "a1");
            return (Criteria)this;
        }

        public Criteria andA1LessThanOrEqualTo(Integer value) {
            addCriterion("a1 <=", value, "a1");
            return (Criteria)this;
        }

        public Criteria andA1In(List<Integer> values) {
            addCriterion("a1 in", values, "a1");
            return (Criteria)this;
        }

        public Criteria andA1NotIn(List<Integer> values) {
            addCriterion("a1 not in", values, "a1");
            return (Criteria)this;
        }

        public Criteria andA1Between(Integer value1, Integer value2) {
            addCriterion("a1 between", value1, value2, "a1");
            return (Criteria)this;
        }

        public Criteria andA1NotBetween(Integer value1, Integer value2) {
            addCriterion("a1 not between", value1, value2, "a1");
            return (Criteria)this;
        }

        public Criteria andA2IsNull() {
            addCriterion("a2 is null");
            return (Criteria)this;
        }

        public Criteria andA2IsNotNull() {
            addCriterion("a2 is not null");
            return (Criteria)this;
        }

        public Criteria andA2EqualTo(String value) {
            addCriterion("a2 =", value, "a2");
            return (Criteria)this;
        }

        public Criteria andA2NotEqualTo(String value) {
            addCriterion("a2 <>", value, "a2");
            return (Criteria)this;
        }

        public Criteria andA2GreaterThan(String value) {
            addCriterion("a2 >", value, "a2");
            return (Criteria)this;
        }

        public Criteria andA2GreaterThanOrEqualTo(String value) {
            addCriterion("a2 >=", value, "a2");
            return (Criteria)this;
        }

        public Criteria andA2LessThan(String value) {
            addCriterion("a2 <", value, "a2");
            return (Criteria)this;
        }

        public Criteria andA2LessThanOrEqualTo(String value) {
            addCriterion("a2 <=", value, "a2");
            return (Criteria)this;
        }

        public Criteria andA2Like(String value) {
            addCriterion("a2 like", value, "a2");
            return (Criteria)this;
        }

        public Criteria andA2NotLike(String value) {
            addCriterion("a2 not like", value, "a2");
            return (Criteria)this;
        }

        public Criteria andA2In(List<String> values) {
            addCriterion("a2 in", values, "a2");
            return (Criteria)this;
        }

        public Criteria andA2NotIn(List<String> values) {
            addCriterion("a2 not in", values, "a2");
            return (Criteria)this;
        }

        public Criteria andA2Between(String value1, String value2) {
            addCriterion("a2 between", value1, value2, "a2");
            return (Criteria)this;
        }

        public Criteria andA2NotBetween(String value1, String value2) {
            addCriterion("a2 not between", value1, value2, "a2");
            return (Criteria)this;
        }
    }

    /**
     * This class was generated by MyBatis Generator. This class corresponds to the database table tbl_a
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator. This class corresponds to the database table tbl_a
     * @mbggenerated
     */
    public static class Criterion {

        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition=condition;
            this.typeHandler=null;
            this.noValue=true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition=condition;
            this.value=value;
            this.typeHandler=typeHandler;
            if(value instanceof List<?>) {
                this.listValue=true;
            } else {
                this.singleValue=true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition=condition;
            this.value=value;
            this.secondValue=secondValue;
            this.typeHandler=typeHandler;
            this.betweenValue=true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}