package com.oneapm.atomikos.b.mapper;

import com.oneapm.atomikos.b.domain.TblB;
import com.oneapm.atomikos.b.domain.TblBCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TblBMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_b
     * @mbggenerated
     */
    int countByExample(TblBCriteria example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_b
     * @mbggenerated
     */
    int deleteByExample(TblBCriteria example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_b
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer b1);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_b
     * @mbggenerated
     */
    int insert(TblB record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_b
     * @mbggenerated
     */
    int insertSelective(TblB record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_b
     * @mbggenerated
     */
    List<TblB> selectByExample(TblBCriteria example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_b
     * @mbggenerated
     */
    TblB selectByPrimaryKey(Integer b1);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_b
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TblB record, @Param("example") TblBCriteria example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_b
     * @mbggenerated
     */
    int updateByExample(@Param("record") TblB record, @Param("example") TblBCriteria example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_b
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TblB record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_b
     * @mbggenerated
     */
    int updateByPrimaryKey(TblB record);
}